name: CD
on:
  - push
  - workflow_dispatch

jobs:
  deploy:
    name: Deploy to NuxtHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build site
        run: bun run build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
